"""
Django settings for consultores project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'maejl8q70awfgkz#zr-kzrtqm)q@nri9^%p94o$h&phjnsqv#r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'storages',
    'schema',
)

# Storage
MEDIA_ROOT = 'https://consultorespatrimoniales.blob.core.windows.net/'
MEDIA_URL = 'https://consultorespatrimoniales.blob.core.windows.net/'
### COMMENT TO USE LOCAL STORAGE / UNCOMMENT TO USE AZURE STORAGE SERVICES
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

# STATICFILES_STORAGE = 'storages.backends.azure_storage.AzureStorage'

### COMMENT TO USE LOCAL STORAGE / UNCOMMENT TO USE AZURE STORAGE SERVICES
AZURE_ACCOUNT_NAME = 'consultorespatrimoniales'
AZURE_ACCOUNT_KEY = 'OEEYlVZGFK0VqPGqpcaNZIjeomV9gOv1z/daQ2lWIMJLkqw+m+I6Dez0VyTXWiIMkFknu+VnfOfyqr78SmY5nA=='
AZURE_CONTAINER = 'cotizaciones'

#For email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp-mail.outlook.com'

EMAIL_HOST_USER = 'consultorespatrimonialesdebug@outlook.com'

#Must generate specific password for your app in [gmail settings][1]
EMAIL_HOST_PASSWORD = 'ConsultoresPatrimoniales'

#Must generate specific password for your app in [gmail settings][1]
EMAIL_PORT = 25

#This did the trick
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# AUTH_USER_MODEL = 'schema.Usuario'

LOGIN_URL = '/'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'consultores.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'consultores.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'consultores_patrimoniales',
        'USER': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
           'init_command': 'SET storage_engine=INNODB',
        }
     }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Mexico/General'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'